[project]
name = 'counter'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[contracts.blockchain]
path = 'contracts/blockchain.clar'
clarity_version = 3
epoch = 3.1

[contracts.miner]
path = 'contracts/miner.clar'
clarity_version = 3
epoch = 3.1

[contracts.pool]
path = 'contracts/pool.clar'
clarity_version = 3
epoch = 3.1

[contracts.slotto-coin]
path = 'contracts/slotto-coin.clar'
clarity_version = 3
epoch = 3.1

[contracts.slotto-oracle]
path = 'contracts/slotto-oracle.clar'
clarity_version = 3
epoch = 3.1

[contracts.trait-blockchain]
path = 'contracts/trait-blockchain.clar'
clarity_version = 3
epoch = 3.1

[contracts.trait-oracle]
path = 'contracts/trait-oracle.clar'
clarity_version = 3
epoch = 3.1

[contracts.vrf]
path = 'contracts/vrf.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
